/** @type {import('tailwindcss').Config} */

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      poppins: ["Poppins", "sans-serif"],
      fredoka: ["Fredoka", "sans-serif"],
      opensans: ["Open Sans", "sans-serif"],
      raleway: ["Raleway", "sans-serif"],
      cabin: ["Cabin", "sans-serif"],
    },
    extend: {
      animation: {
        shimmer: "shimmer 1.5s infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        brand: {
          50: '#EAF3FF',
          100: '#B9D5FF',
          200: '#8AB8FF',
          300: '#5A9AFF',
          400: '#2B7CFF',
          500: '#005CE6',
          600: '#0248C7',
          700: '#013593',
          800: '#012260',
          900: '#000E2C',
        },
        'brand-secondary': {
          50: '#FFF0E6',
          100: '#FFD1B3',
          200: '#FFB380',
          300: '#FF944D',
          400: '#FF751A',
          500: '#E65C00',
          600: '#B34700',
          700: '#803300',
          800: '#4D1F00',
          900: '#1A0A00',
        },
        'brand-info': {
          50: '#E6F7FF',
          100: '#B3E0FF',
          200: '#80CCFF',
          300: '#4DB8FF',
          400: '#1AA3FF',
          500: '#0088CC',
          600: '#006BB3',
          700: '#004D80',
          800: '#002E4D',
          900: '#00101A',
        },
        'brand-success': {
          50: '#E6FFFA',
          100: '#B3FFED',
          200: '#80FFE0',
          300: '#4DFFD3',
          400: '#1AFFC6',
          500: '#00CC99',
          600: '#009973',
          700: '#00664D',
          800: '#003326',
          900: '#001A13',
        },
        'brand-warning': {
          50: '#FFFBE6',
          100: '#FFF1B3',
          200: '#FFE680',
          300: '#FFDC4D',
          400: '#FFD11A',
          500: '#FFCC00',
          600: '#B38F00',
          700: '#806600',
          800: '#4D3D00',
          900: '#1A1400',
        },
        'brand-danger': {
          50: '#FFE6E6',
          100: '#FFB3B3',
          200: '#FF8080',
          300: '#FF4D4D',
          400: '#FF1A1A',
          500: '#E60000',
          600: '#B30000',
          700: '#800000',
          800: '#4D0000',
          900: '#1A0000',
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
