export type PaymentPlan = {
  _id: string;
  planKey: string;
  rail: "paystack_ngn" | "creem_usd";
  name: string;
  description: string;
  planType: "subscription" | "credit_pack";
  amount: number;
  amountUsd: number;
  currency: string;
  features: string[];
  credits: number;
  creditExpiry: string;
  duration: string;
  maxUsers: number;
  overageRate: string;
  highlight: boolean;
  sortOrder: number;
  validityMonths: number;
  billingLabel: string;
  displayInterval: string;
  creemProductId?: string;
  creemProductType?: string;
  createdAt: string;
};
